on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libharfbuzz-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff-dev \
            libxml2-dev \
            libgit2-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libicu-dev \
            libcairo2-dev \
            libxt-dev \
            pandoc

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - name: Restore R environment with renv
        run: Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Build pkgdown site (local environment)
        run: |
          Rscript -e 'options(pkgdown.use_ragg = TRUE); pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE, devel = FALSE, quiet = FALSE)'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: github.event_name != 'pull_request'
        with:
          clean: false
          branch: gh-pages
          folder: docs
